<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jlshell.link</groupId>
        <artifactId>jlshell-link-plugins-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <artifactId>link-plugin-distribution</artifactId>
    <packaging>pom</packaging>
    <dependencies>
        <dependency>
            <groupId>com.jlshell.link</groupId>
            <artifactId>link-program-plugin</artifactId>
            <version>${project.version}</version>
            <classifier>fat</classifier>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
                <executions>
                    <execution>
                        <id>collect-plugin-jars</id>
                        <phase>package</phase>
                        <goals><goal>copy-dependencies</goal></goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/plugins</outputDirectory>
                            <includeGroupIds>com.jlshell.link</includeGroupIds>
                            <includeArtifactIds>link-program-plugin</includeArtifactIds>
                            <includeClassifiers>fat</includeClassifiers>
                            <excludeTransitive>true</excludeTransitive>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
